MANTA-4597 fixes for move-a-repo to handle my not having a local clone in the usual places

diff --git a/bin/move-a-repo b/bin/move-a-repo
--- a/bin/move-a-repo
+++ b/bin/move-a-repo
@@ -30,7 +30,7 @@ fi
 set -o errexit
 set -o pipefail
 
-VERSION=1.0.0
+VERSION=1.0.1
 
 
 # ---- support functions
@@ -109,9 +109,16 @@ done
 
 echo ""
 echo "## Update 'not use GitHub PRs' possible hits in README.md et al"
-echo "Checking '~/joy/$baseName' for candidate hits:"
-(cd ~/joy/$baseName && (rg -g '!deps' 'not use GitHub PRs' || true))
-(cd ~/joy/$baseName && (rg -g '!deps' 'cr.joyent.us' || true))
+checkDir=$HOME/all/$baseName
+if [[ ! -d $checkDir ]]; then
+    checkDir=$HOME/joy/$baseName
+fi
+if [[ ! -d $checkDir ]]; then
+    fatal "cannot find a clone of $repoName to check for Gerrit doc hits"
+fi
+echo "Checking '$checkDir' for candidate hits:"
+(cd $checkDir && (rg -g '!deps' 'not use GitHub PRs' || true))
+(cd $checkDir && (rg -g '!deps' 'cr.joyent.us' || true))
 cat <<EOM
 
 If there were candidate hits, please create a PR to update those:
