MANTA-4595: update cr.joyent.us archive to latest

diff --git a/archive/6957/currentPatchSet.diff b/archive/6957/currentPatchSet.diff
--- a/archive/6957/currentPatchSet.diff
+++ b/archive/6957/currentPatchSet.diff
@@ -1,22 +1,24 @@
-From 9c2939c6487ff4cecfcb98d8a86bdec36575403f Mon Sep 17 00:00:00 2001
+From 4e3fe4af997ffbdbfa15e6b9068549f79e4fe8a9 Mon Sep 17 00:00:00 2001
 From: Tim Foster <tim.foster@joyent.com>
-Date: Mon, 7 Oct 2019 11:46:16 +0100
-Subject: [PATCH] OS-6146 Update copyright date in /etc/release
+Date: Tue, 8 Oct 2019 17:59:36 +0100
+Subject: [PATCH] OS-6146 Update copyright date in /etc/release Reviewed by:
+ John Levon <john.levon@joyent.com> Approved by: John Levon
+ <john.levon@joyent.com>
 
 ---
- src/Makefile                   |  7 +++++--
- src/etc/notices/COPYRIGHT      |  3 +--
- tools/build_etcrelease         | 25 ++++++++++++++++++++-----
- tools/build_live               |  4 ++--
- tools/etc_release.template.txt |  4 ----
- 5 files changed, 28 insertions(+), 15 deletions(-)
+ src/Makefile                   |  7 +++-
+ src/etc/notices/COPYRIGHT      |  3 +-
+ tools/build_etcrelease         | 71 ++++++++++++++++++++++------------
+ tools/build_live               |  5 +--
+ tools/etc_release.template.txt |  4 --
+ 5 files changed, 54 insertions(+), 36 deletions(-)
  delete mode 100644 tools/etc_release.template.txt
 
 diff --git a/src/Makefile b/src/Makefile
-index f1a5b45e..af1469e2 100644
+index d389830c..5125aceb 100644
 --- a/src/Makefile
 +++ b/src/Makefile
-@@ -351,10 +351,11 @@ LIBSDC_TARGETS = \
+@@ -353,10 +353,11 @@ LIBSDC_TARGETS = \
  
  ETC_TARGETS = \
  	etc/nodename \
@@ -29,7 +31,7 @@ index f1a5b45e..af1469e2 100644
  BHYVE_TARGETS = \
  	bhyve/uefi-csm-rom.bin \
  	bhyve/uefi-rom.bin \
-@@ -375,7 +376,7 @@ check : TARGET = check
+@@ -377,7 +378,7 @@ check : TARGET = check
  
  all: $(TARGETS) $(USR_LIB_TARGETS) $(SMARTDC_TARGETS) \
      $(SMARTDC_LIB_TARGETS) $(LIBSDC_TARGETS) $(ETC_TARGETS) \
@@ -38,7 +40,7 @@ index f1a5b45e..af1469e2 100644
  
  
  $(SUBDIRS): FRC
-@@ -499,6 +500,8 @@ install: all $(SUBDIRS)
+@@ -501,6 +502,8 @@ install: all $(SUBDIRS)
  	mv $(NOMKNOD_ROOT64)/$(NOMKNOD_64) $(NOMKNOD_ROOT64)/$(NOMKNOD_SO)
  	mkdir -p $(DESTDIR)/usr/share/bhyve
  	cp $(BHYVE_TARGETS) $(DESTDIR)/usr/share/bhyve
@@ -59,18 +61,18 @@ index 1834bac7..a98f3199 100644
  Copyright © 2010 Oracle, Inc., All rights reserved.
  
 diff --git a/tools/build_etcrelease b/tools/build_etcrelease
-index e037b0c1..2cbfb00a 100755
+index e037b0c1..2d019b47 100755
 --- a/tools/build_etcrelease
 +++ b/tools/build_etcrelease
-@@ -28,8 +28,14 @@ ber_arg0=$(basename $0)
+@@ -27,9 +27,12 @@ export PATH=/opt/local/bin/:$PATH
+ ber_arg0=$(basename $0)
  ber_wsroot=$(cd "$(dirname "$0")/.." && pwd)
  ber_first=true
- ber_version=$1
+-ber_version=$1
 -ber_template=$2
-+ber_year=$2
-+ber_template=$3
- ber_template_data=
-+ber_default_template="                     SmartOS %%VERSION%% x86_64
+-ber_template_data=
++
++ber_template="                     SmartOS %%VERSION%% x86_64
 +                       Copyright %%YEAR%% Joyent, Inc.
 +
 +  Built with the following components:
@@ -78,65 +80,104 @@ index e037b0c1..2cbfb00a 100755
  
  function fatal
  {
-@@ -117,13 +123,14 @@ function get_status
- #
- #	1. Generating the "/etc/release" file which starts with a header and
- #	   includes the JSON manifest underneath.  To use this mode, the
+@@ -112,31 +115,49 @@ function get_status
+ 	return 0
+ }
+ 
+-#
+-# We support two modes of operation:
+-#
+-#	1. Generating the "/etc/release" file which starts with a header and
+-#	   includes the JSON manifest underneath.  To use this mode, the
 -#	   caller must provide a VERSION and a TEMPLATE_FILE argument.
-+#	   caller must provide a VERSION and YEAR and optionally,
-+#      a TEMPLATE_FILE argument.
- #
- #	2. Generating the bare JSON for the "boot_archive.gitstatus" file.
- #	   This mode is active when no arguments are passed.
- #
+-#
+-#	2. Generating the bare JSON for the "boot_archive.gitstatus" file.
+-#	   This mode is active when no arguments are passed.
+-#
 -if (( $# != 0 && $# != 2 )); then
 -	fatal "usage: $ber_arg0 [ VERSION TEMPLATE_FILE ]"
-+if [[ $# != 0 && $# -gt 3 ]]; then
-+	fatal "usage: $ber_arg0 [VERSION YEAR TEMPLATE_FILE ]"
- fi
+-fi
++function usage {
++	echo "Usage: build_etcrelease <options>"
++	echo "    -g                  emit gitstatus.json content"
++	echo "    -h                  print this message"
++	echo "    -v <version>        emit an etc/release file with <version>,"
++	echo "                        including the gistatus.json content."
++	echo ""
++}
  
- if [[ -n $ber_template ]]; then
-@@ -132,11 +139,19 @@ if [[ -n $ber_template ]]; then
- 	fi
+-if [[ -n $ber_template ]]; then
+-	if [[ ! -f $ber_template ]]; then
+-		fatal "could not find template file \"$ber_template\""
+-	fi
++while getopts "ghv:" opt; do
++	case "${opt}" in
++		g)
++			do_gitstatus=true
++			;;
++		h)
++			do_help=true
++			;;
++		v)
++			ber_version=$OPTARG
++			;;
++		*)
++			warn "unknown option ${opt}"
++			usage
++	esac
++done
++shift $((OPTIND - 1))
  
- 	if ! ber_template_data=$(sed -e "s,%%VERSION%%,$ber_version,g" \
+-	if ! ber_template_data=$(sed -e "s,%%VERSION%%,$ber_version,g" \
 -	    "$ber_template"); then
-+	    -e "s,%%YEAR%%,$ber_year,g" "$ber_template"); then
- 		fatal "could not load template file \"$ber_template\""
- 	fi
- 
- 	printf '%s\n\n' "$ber_template_data"
+-		fatal "could not load template file \"$ber_template\""
+-	fi
++if [[ -z "$do_help" && -z "$do_gitstatus" && -z "$ber_version" ]]; then
++	usage
++	exit 2
++fi
 +
-+elif [[ -n "$ber_version" ]]; then
-+	if ! ber_template_data=$(echo "$ber_default_template" | \
++if [[ -n "$do_help" ]]; then
++	usage
++	exit 2
++fi
+ 
+-	printf '%s\n\n' "$ber_template_data"
++if [[ -n "$ber_version" ]]; then
++	ber_year=$(date +%Y)
++	ber_content=$(echo "$ber_template" | \
 +	    sed -e "s,%%VERSION%%,$ber_version,g" \
-+		-e "s,%%YEAR%%,$ber_year,g"); then
-+		fatal "could not generate default template"
-+	fi
-+	printf '%s\n\n' "$ber_template_data"
++		-e "s,%%YEAR%%,$ber_year,g");
++	printf '%s\n\n' "$ber_content"
  fi
  
  ( printf '[\n'
 diff --git a/tools/build_live b/tools/build_live
-index ed5528d4..48d41e6e 100755
+index ed5528d4..d7551492 100755
 --- a/tools/build_live
 +++ b/tools/build_live
-@@ -414,8 +414,8 @@ function bi_create_password
+@@ -414,14 +414,13 @@ function bi_create_password
  #
  function bi_gen_version_files
  {
 -	local etcrelease_template="$bi_wsroot/tools/etc_release.template.txt"
  	local build_etcrelease="$bi_wsroot/tools/build_etcrelease"
-+	local etcrelease_year=$(date +%Y)
  	local bvfile="$bi_mnt_root/etc/versions/build"
  	local gitstatus="$bi_out_dir/gitstatus.json"
  
-@@ -437,7 +437,7 @@ function bi_gen_version_files
+ 	bi_emit_start 'Building version files'
+ 
+-	"$build_etcrelease" >"$gitstatus" ||
++	"$build_etcrelease" -g >"$gitstatus" ||
+ 	    fail "could not generate $gitstatus"
+ 
+ 	pfexec cp "$gitstatus" "$bi_archive.gitstatus" ||
+@@ -437,7 +436,7 @@ function bi_gen_version_files
  	# permission to write in the mounted image using regular shell
  	# redirection.
  	#
 -	"$build_etcrelease" "$bi_buildstamp" "$etcrelease_template" |
-+	"$build_etcrelease" "$bi_buildstamp" "$etcrelease_year" |
++	"$build_etcrelease" -v "$bi_buildstamp" |
  	    pfexec /usr/bin/tee "$bi_mnt_root/etc/release" >/dev/null ||
  	     fail 'failed to build "/etc/release" file'
  
